# Generated by Django 4.2.2 on 2023-07-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
