# Generated by Django 4.2.2 on 2023-06-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_alter_car_table_alter_carmodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fueltype',
            },
        ),
        migrations.CreateModel(
            name='CModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fueltype', models.ManyToManyField(to='relationship.fueltype')),
            ],
            options={
                'db_table': 'cmodel',
            },
        ),
    ]
